### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/types-base_support#1]
When trying to compile with amake, the process breaks when includes of "base/*.hpp" cannot be resolved. Probably some path issues or something.

```
In file included from /root/esrocos_workspace/types/base_support/src/asn1AngleConvert.cpp:11:0:
/root/esrocos_workspace/types/base_support/src/asn1AngleConvert.hpp:15:26: fatal error: base/Angle.hpp: No such file or directory
 #include "base/Angle.hpp"
                          ^

In file included from /root/esrocos_workspace/types/base_support/src/asn1BodyStateConvert.cpp:11:0:
/root/esrocos_workspace/types/base_support/src/asn1BodyStateConvert.hpp:15:38: fatal error: base/samples/BodyState.hpp: No such file or directory
 #include "base/samples/BodyState.hpp
```

**Comment by Kynneb** [comment]
@mmunoz-gmv  maybe you might have a look into that (and into the proposed fix https://github.com/ESROCOS/types-base_support/pull/2 ?)

**Comment by mmunoz-gmv** [comment]
The files not found belong to Rock's base types package. Please, verify that it's correctly installed.

**Comment by Kynneb** [comment]
I did and they are. In fact the error is fixed as soon as the install-dir/include is added as include dir in cmake as it is done in the PR. But perhaps I am missing something more obvious?

**Comment by mmunoz-gmv** [comment]
I've added the include dir.

**Comment by Kynneb** [comment]
Thanks, tested and worked.
