### ISSUE TITLE
Change in CMakeLists (or corresponding function in esrocos.cmake) breaks build

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/types-base_support#3]
Currently building of types-base_support breaks because of an error corresponding to the cmake function esrocos_asn1_types_package. The error is, that the outputdirectory "asn1" does not exist and the target base_support_local_types therefore cannot be built.

**Comment by mmunoz-gmv** [comment]
Added creation of the directory in the cmake commands. Please, check if it solves the problem for you.

**Comment by Kynneb** [comment]
Hey, unfortunately not, it still breaks in configuration phase

```
CMake Error at src/CMakeLists.txt:98 (add_dependencies):
  The dependency target "base_support_local_types" of target "base_support"
  does not exist.
```

**Comment by mmunoz-gmv** [comment]
We're ready to merge the branch "autogenerated" of types/base and types/base_support into main, which should solve the problem, I think. However, this is a big change that will impact any code that is using the current master branches. Is it ok on DFKI's side to go ahead with the merge (on Monday)? You can test it by checking out the branch "autogenerated" for those two packages.

In the meanwhile, to fix the specific error that you're having you should rename the target base_support_local_types to base_support_local_types_generate_c. I cannot guarantee that this won't lead you to a new error, though.

**Comment by Kynneb** [comment]
I added a branch ``test_autogenerated`` in the buildconf repo with an overrides.yml that sets the branches for types/base and types/base_support to autogenerated and started a test installation on our local build server so hopefully I will be able to report on that positively.

**Comment by Kynneb** [comment]
It seems to work for types/base and types/base_support but will break types/driver due to the changes in the macro file.

**Comment by mmunoz-gmv** [comment]
types/driver comes from SARGON and is no longer needed in ESROCOS.

**Comment by Kynneb** [comment]
And it seems the same problem holds for types/core and types/sensor_samples as well as types/sensor_samples_support

**Comment by Kynneb** [comment]
However, types/base and types/base_support on branch autogenerated compile fine again
