### ISSUE TITLE
Failed include <base/wrappers/Eigen.hpp>

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/types-base_support#5]
Build fails with missing include. The file can be found in ${cmake_install_prefix}/include/orocos/base/wrappers/Eigen.hpp - so the include should either reflect that or ${cmake_install_prefix}/include/orocos must be set as include dir. Also this dependency should probably be reflected somehow in the manifest.

**Comment by mmunoz-gmv** [comment]
Is this still happening or can it be closed?

**Comment by RaquelJalvo** [comment]
In the CMakeLists.txt appears this include directory and in the manifest.xml there is a dependency with base/orogen/types. I am closing it.
